// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hydratx.proto

package hydra

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoCompleteTransaction struct {
	Txid                 []byte                                `protobuf:"bytes,1,opt,name=Txid,proto3" json:"Txid,omitempty"`
	Hex                  []byte                                `protobuf:"bytes,2,opt,name=Hex,proto3" json:"Hex,omitempty"`
	Blocktime            uint64                                `protobuf:"varint,3,opt,name=Blocktime,proto3" json:"Blocktime,omitempty"`
	Locktime             uint32                                `protobuf:"varint,4,opt,name=Locktime,proto3" json:"Locktime,omitempty"`
	Height               uint32                                `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Vin                  []*ProtoCompleteTransaction_VinType   `protobuf:"bytes,6,rep,name=Vin,proto3" json:"Vin,omitempty"`
	Vout                 []*ProtoCompleteTransaction_VoutType  `protobuf:"bytes,7,rep,name=Vout,proto3" json:"Vout,omitempty"`
	Version              int32                                 `protobuf:"varint,8,opt,name=Version,proto3" json:"Version,omitempty"`
	Receipt              *ProtoCompleteTransaction_ReceiptType `protobuf:"bytes,9,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ProtoCompleteTransaction) Reset()         { *m = ProtoCompleteTransaction{} }
func (m *ProtoCompleteTransaction) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction) ProtoMessage()    {}
func (*ProtoCompleteTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6efb3ced3feb72e4, []int{0}
}

func (m *ProtoCompleteTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction.Merge(m, src)
}
func (m *ProtoCompleteTransaction) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction.Size(m)
}
func (m *ProtoCompleteTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction proto.InternalMessageInfo

func (m *ProtoCompleteTransaction) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetHex() []byte {
	if m != nil {
		return m.Hex
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetBlocktime() uint64 {
	if m != nil {
		return m.Blocktime
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetVin() []*ProtoCompleteTransaction_VinType {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetVout() []*ProtoCompleteTransaction_VoutType {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetReceipt() *ProtoCompleteTransaction_ReceiptType {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type ProtoCompleteTransaction_VinType struct {
	Coinbase             string   `protobuf:"bytes,1,opt,name=Coinbase,proto3" json:"Coinbase,omitempty"`
	Txid                 []byte   `protobuf:"bytes,2,opt,name=Txid,proto3" json:"Txid,omitempty"`
	Vout                 uint32   `protobuf:"varint,3,opt,name=Vout,proto3" json:"Vout,omitempty"`
	ScriptSigHex         []byte   `protobuf:"bytes,4,opt,name=ScriptSigHex,proto3" json:"ScriptSigHex,omitempty"`
	Sequence             uint32   `protobuf:"varint,5,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Addresses            []string `protobuf:"bytes,6,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCompleteTransaction_VinType) Reset()         { *m = ProtoCompleteTransaction_VinType{} }
func (m *ProtoCompleteTransaction_VinType) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction_VinType) ProtoMessage()    {}
func (*ProtoCompleteTransaction_VinType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6efb3ced3feb72e4, []int{0, 0}
}

func (m *ProtoCompleteTransaction_VinType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_VinType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_VinType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_VinType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_VinType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_VinType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_VinType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_VinType.Size(m)
}
func (m *ProtoCompleteTransaction_VinType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_VinType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_VinType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_VinType) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

func (m *ProtoCompleteTransaction_VinType) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *ProtoCompleteTransaction_VinType) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *ProtoCompleteTransaction_VinType) GetScriptSigHex() []byte {
	if m != nil {
		return m.ScriptSigHex
	}
	return nil
}

func (m *ProtoCompleteTransaction_VinType) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ProtoCompleteTransaction_VinType) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ProtoCompleteTransaction_VoutType struct {
	ValueSat             []byte   `protobuf:"bytes,1,opt,name=ValueSat,proto3" json:"ValueSat,omitempty"`
	N                    uint32   `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	ScriptPubKeyHex      []byte   `protobuf:"bytes,3,opt,name=ScriptPubKeyHex,proto3" json:"ScriptPubKeyHex,omitempty"`
	Addresses            []string `protobuf:"bytes,4,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCompleteTransaction_VoutType) Reset()         { *m = ProtoCompleteTransaction_VoutType{} }
func (m *ProtoCompleteTransaction_VoutType) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction_VoutType) ProtoMessage()    {}
func (*ProtoCompleteTransaction_VoutType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6efb3ced3feb72e4, []int{0, 1}
}

func (m *ProtoCompleteTransaction_VoutType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_VoutType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_VoutType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_VoutType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_VoutType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_VoutType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_VoutType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_VoutType.Size(m)
}
func (m *ProtoCompleteTransaction_VoutType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_VoutType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_VoutType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_VoutType) GetValueSat() []byte {
	if m != nil {
		return m.ValueSat
	}
	return nil
}

func (m *ProtoCompleteTransaction_VoutType) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *ProtoCompleteTransaction_VoutType) GetScriptPubKeyHex() []byte {
	if m != nil {
		return m.ScriptPubKeyHex
	}
	return nil
}

func (m *ProtoCompleteTransaction_VoutType) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ProtoCompleteTransaction_ReceiptType struct {
	GasUsed              []byte                                          `protobuf:"bytes,1,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	GasLimit             []byte                                          `protobuf:"bytes,2,opt,name=GasLimit,proto3" json:"GasLimit,omitempty"`
	GasPrice             []byte                                          `protobuf:"bytes,3,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	Status               []byte                                          `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Log                  []*ProtoCompleteTransaction_ReceiptType_LogType `protobuf:"bytes,5,rep,name=Log,proto3" json:"Log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ProtoCompleteTransaction_ReceiptType) Reset()         { *m = ProtoCompleteTransaction_ReceiptType{} }
func (m *ProtoCompleteTransaction_ReceiptType) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction_ReceiptType) ProtoMessage()    {}
func (*ProtoCompleteTransaction_ReceiptType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6efb3ced3feb72e4, []int{0, 2}
}

func (m *ProtoCompleteTransaction_ReceiptType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Size(m)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_ReceiptType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_ReceiptType) GetGasUsed() []byte {
	if m != nil {
		return m.GasUsed
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetLog() []*ProtoCompleteTransaction_ReceiptType_LogType {
	if m != nil {
		return m.Log
	}
	return nil
}

type ProtoCompleteTransaction_ReceiptType_LogType struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Topics               [][]byte `protobuf:"bytes,3,rep,name=Topics,proto3" json:"Topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) Reset() {
	*m = ProtoCompleteTransaction_ReceiptType_LogType{}
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoCompleteTransaction_ReceiptType_LogType) ProtoMessage() {}
func (*ProtoCompleteTransaction_ReceiptType_LogType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6efb3ced3feb72e4, []int{0, 2, 0}
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Size(m)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoCompleteTransaction)(nil), "hydra.ProtoCompleteTransaction")
	proto.RegisterType((*ProtoCompleteTransaction_VinType)(nil), "hydra.ProtoCompleteTransaction.VinType")
	proto.RegisterType((*ProtoCompleteTransaction_VoutType)(nil), "hydra.ProtoCompleteTransaction.VoutType")
	proto.RegisterType((*ProtoCompleteTransaction_ReceiptType)(nil), "hydra.ProtoCompleteTransaction.ReceiptType")
	proto.RegisterType((*ProtoCompleteTransaction_ReceiptType_LogType)(nil), "hydra.ProtoCompleteTransaction.ReceiptType.LogType")
}

func init() { proto.RegisterFile("hydratx.proto", fileDescriptor_6efb3ced3feb72e4) }

var fileDescriptor_6efb3ced3feb72e4 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0x71, 0xe4, 0xc4, 0xc9, 0x24, 0xa1, 0x45, 0x87, 0x22, 0x42, 0x0f, 0x66, 0x2f, 0x35,
	0x14, 0x72, 0xd8, 0x3d, 0x15, 0x7a, 0x69, 0xb7, 0xcb, 0x2e, 0xd4, 0x6c, 0x83, 0x9c, 0xfa, 0xae,
	0x38, 0x83, 0x57, 0x34, 0xb1, 0x5c, 0x4b, 0x86, 0x04, 0xfa, 0x0e, 0x7d, 0x8f, 0xf6, 0x25, 0x8b,
	0x14, 0xd9, 0xfb, 0x07, 0xca, 0xb2, 0x37, 0xfd, 0x46, 0xfe, 0xa4, 0x4f, 0xdf, 0x8c, 0x61, 0x7e,
	0x77, 0xdc, 0x36, 0xc2, 0x1c, 0x96, 0x75, 0xa3, 0x8c, 0xa2, 0x43, 0x87, 0x67, 0x7f, 0x22, 0x60,
	0x2b, 0x5b, 0xb8, 0x54, 0xfb, 0x7a, 0x87, 0x06, 0xd7, 0x8d, 0xa8, 0xb4, 0x28, 0x8c, 0x54, 0x15,
	0xa5, 0x10, 0xae, 0x0f, 0x72, 0xcb, 0x82, 0x38, 0x48, 0x66, 0xdc, 0xad, 0xe9, 0x6b, 0x20, 0x37,
	0x78, 0x60, 0x03, 0x57, 0xb2, 0x4b, 0xfa, 0x16, 0x26, 0x9f, 0x77, 0xaa, 0xf8, 0x61, 0xe4, 0x1e,
	0x19, 0x89, 0x83, 0x24, 0xe4, 0xf7, 0x05, 0xba, 0x80, 0x71, 0xda, 0x6d, 0x86, 0x71, 0x90, 0xcc,
	0x79, 0xcf, 0xf4, 0x0d, 0x8c, 0x6e, 0x50, 0x96, 0x77, 0x86, 0x0d, 0xdd, 0x8e, 0x27, 0xfa, 0x01,
	0x48, 0x2e, 0x2b, 0x36, 0x8a, 0x49, 0x32, 0x3d, 0x7f, 0xb7, 0x74, 0x4e, 0x97, 0xff, 0x73, 0xb9,
	0xcc, 0x65, 0xb5, 0x3e, 0xd6, 0xc8, 0xad, 0x86, 0x7e, 0x84, 0x30, 0x57, 0xad, 0x61, 0x91, 0xd3,
	0x26, 0xcf, 0x6a, 0x55, 0x6b, 0x9c, 0xd8, 0xa9, 0x28, 0x83, 0x28, 0xc7, 0x46, 0x4b, 0x55, 0xb1,
	0x71, 0x1c, 0x24, 0x43, 0xde, 0x21, 0xbd, 0x82, 0x88, 0x63, 0x81, 0xb2, 0x36, 0x6c, 0x12, 0x07,
	0xc9, 0xf4, 0xfc, 0xfd, 0x73, 0x47, 0xfb, 0xcf, 0xdd, 0xe9, 0x9d, 0x76, 0xf1, 0x37, 0x80, 0xc8,
	0xfb, 0xb5, 0xc9, 0x5c, 0x2a, 0x59, 0x6d, 0x84, 0x46, 0x97, 0xf0, 0x84, 0xf7, 0xdc, 0x27, 0x3f,
	0x78, 0x90, 0x3c, 0xf5, 0x4f, 0x23, 0x2e, 0xab, 0x93, 0xe1, 0x33, 0x98, 0x65, 0x45, 0x23, 0x6b,
	0x93, 0xc9, 0xd2, 0xb6, 0x25, 0x74, 0xdf, 0x3f, 0xaa, 0xd9, 0x7b, 0x32, 0xfc, 0xd9, 0x62, 0x55,
	0xa0, 0xcf, 0xb9, 0x67, 0xdb, 0xbb, 0x4f, 0xdb, 0x6d, 0x83, 0x5a, 0xa3, 0x76, 0x79, 0x4f, 0xf8,
	0x7d, 0x61, 0xf1, 0x0b, 0xc6, 0x5d, 0x40, 0xf6, 0x94, 0x5c, 0xec, 0x5a, 0xcc, 0x84, 0xf1, 0xf3,
	0xd0, 0x33, 0x9d, 0x41, 0x70, 0xeb, 0xac, 0xce, 0x79, 0x70, 0x4b, 0x13, 0x78, 0x75, 0xba, 0x7f,
	0xd5, 0x6e, 0xbe, 0xe2, 0xd1, 0xda, 0x22, 0x4e, 0xf0, 0xb4, 0xfc, 0xf8, 0xf6, 0xf0, 0xe9, 0xed,
	0xbf, 0x07, 0x30, 0x7d, 0x10, 0xa2, 0x6d, 0xce, 0xb5, 0xd0, 0xdf, 0x35, 0x76, 0x03, 0xd9, 0xa1,
	0xf5, 0x76, 0x2d, 0x74, 0x2a, 0xf7, 0xd2, 0xf8, 0xc4, 0x7a, 0xf6, 0x7b, 0xab, 0x46, 0x16, 0xe8,
	0x6d, 0xf4, 0x6c, 0xe7, 0x2f, 0x33, 0xc2, 0xb4, 0xda, 0xe7, 0xe6, 0x89, 0x5e, 0x01, 0x49, 0x55,
	0xc9, 0x86, 0x6e, 0x86, 0x2e, 0x5e, 0xd0, 0xe8, 0x65, 0xaa, 0xca, 0xd3, 0x2c, 0xa6, 0xaa, 0x5c,
	0x7c, 0x83, 0xc8, 0xb3, 0xf5, 0xee, 0x1f, 0xd6, 0x79, 0xf7, 0x68, 0xbb, 0xfa, 0x45, 0x18, 0xd1,
	0x75, 0xda, 0xae, 0xad, 0xaf, 0xb5, 0xaa, 0x65, 0xa1, 0x19, 0x89, 0x89, 0xf5, 0x75, 0xa2, 0xcd,
	0xc8, 0xfd, 0xba, 0x17, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xa4, 0xd6, 0x55, 0xcb, 0x03,
	0x00, 0x00,
}
